# AGDITHA EVALYN LOLONGAN 
## 2109106030 

### mengimport library

In [2]:
import tensorflow as tf

### Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor

In [4]:
random_tensor = tf.random.uniform(shape = (5,5), minval=1, maxval=100, dtype=tf.int32)
random_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[70, 49, 27, 50, 18],
       [70, 10, 59, 58, 68],
       [44, 38, 96, 42, 50],
       [81,  1, 55, 22, 21],
       [94, 91, 45, 60, 64]])>

### Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor 

###  list berisi bil prima

In [5]:
list= [[2, 3, 5, 7, 11], [17, 19, 23, 29, 31], [37, 41, 43, 47, 53], [59, 61, 67, 71, 73], [79, 83, 89, 97, 101]]
prime_tensor = tf.convert_to_tensor(list)
prime_tensor

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  2,   3,   5,   7,  11],
       [ 17,  19,  23,  29,  31],
       [ 37,  41,  43,  47,  53],
       [ 59,  61,  67,  71,  73],
       [ 79,  83,  89,  97, 101]])>

## Tampilkan dimensi dari kedua variable tersebut

In [10]:
print("==Display dimensi variabel==")
random_tensor.shape

==Display dimensi variabel==


TensorShape([5, 5])

In [9]:
print("==Display dimensi variabel==")
prime_tensor.shape

==Display dimensi variabel==


TensorShape([5, 5])

### Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator)

In [11]:
print ("======Penjumlahan=====")
tf.add(random_tensor, prime_tensor)

Penjumlahan


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 72,  52,  32,  57,  29],
       [ 87,  29,  82,  87,  99],
       [ 81,  79, 139,  89, 103],
       [140,  62, 122,  93,  94],
       [173, 174, 134, 157, 165]])>

In [14]:
print ("======Pengurangan=====")
tf.subtract(random_tensor, prime_tensor)

======Pengurangan=====


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 68,  46,  22,  43,   7],
       [ 53,  -9,  36,  29,  37],
       [  7,  -3,  53,  -5,  -3],
       [ 22, -60, -12, -49, -52],
       [ 15,   8, -44, -37, -37]])>

In [15]:
print ("======Pembagian=====")
tf.divide(random_tensor, prime_tensor)

======Pembagian=====


<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[3.50000000e+01, 1.63333333e+01, 5.40000000e+00, 7.14285714e+00,
        1.63636364e+00],
       [4.11764706e+00, 5.26315789e-01, 2.56521739e+00, 2.00000000e+00,
        2.19354839e+00],
       [1.18918919e+00, 9.26829268e-01, 2.23255814e+00, 8.93617021e-01,
        9.43396226e-01],
       [1.37288136e+00, 1.63934426e-02, 8.20895522e-01, 3.09859155e-01,
        2.87671233e-01],
       [1.18987342e+00, 1.09638554e+00, 5.05617978e-01, 6.18556701e-01,
        6.33663366e-01]])>

In [16]:
print ("======Perkalian=====")
tf.multiply(random_tensor, prime_tensor)

======Perkalian=====


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 140,  147,  135,  350,  198],
       [1190,  190, 1357, 1682, 2108],
       [1628, 1558, 4128, 1974, 2650],
       [4779,   61, 3685, 1562, 1533],
       [7426, 7553, 4005, 5820, 6464]])>

In [18]:
print("======Perpangkatan====")
tf.pow(random_tensor, prime_tensor)

======Perpangkatan====


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[       4900,      117649,    14348907,  -434047872, -1480538112],
       [-1614413824, -1981284352, -1569890861, -1610612736,           0],
       [          0,           0,           0,           0,           0],
       [ 1674951025,           1,   670019559,           0,  1997373173],
       [          0,  2092118499,  1697936653,           0,           0]])>

## Tampilkan nilai maksimal dan minimal dari variable random_tensor

In [24]:
maximal = tf.argmax(random_tensor, axis=0)
minimal = tf.argmin(random_tensor, axis=1)
print("locate the maximum :",maximal.numpy())
print("locate the minimal:",minimal.numpy())

locate the maximum : [4 4 2 4 1]
locate the minimal: [4 1 1 1 2]


## Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [21]:
concat = tf.concat([random_tensor, prime_tensor], axis=1)
concat

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[ 70,  49,  27,  50,  18,   2,   3,   5,   7,  11],
       [ 70,  10,  59,  58,  68,  17,  19,  23,  29,  31],
       [ 44,  38,  96,  42,  50,  37,  41,  43,  47,  53],
       [ 81,   1,  55,  22,  21,  59,  61,  67,  71,  73],
       [ 94,  91,  45,  60,  64,  79,  83,  89,  97, 101]])>

## Tampilkan hasil sorting dari kedua variable di atas. (descending)

In [22]:
print ("Descending Variabel random_tensor")
tf.sort(random_tensor, direction="DESCENDING")

Descending Variabel random_tensor


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[70, 50, 49, 27, 18],
       [70, 68, 59, 58, 10],
       [96, 50, 44, 42, 38],
       [81, 55, 22, 21,  1],
       [94, 91, 64, 60, 45]])>

In [23]:
print ("Descending Variabel prime_tensor")
tf.sort(prime_tensor, direction="DESCENDING")

Descending Variabel prime_tensor


<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 11,   7,   5,   3,   2],
       [ 31,  29,  23,  19,  17],
       [ 53,  47,  43,  41,  37],
       [ 73,  71,  67,  61,  59],
       [101,  97,  89,  83,  79]])>